check it
krolik1591/log-to-exel pull request #1
Opened 2022-04-29 21:08 UTC by krolik1591

please

2022-04-29 21:20 UTC, SvineruS requested changes

2022-04-29 21:20 UTC, SvineruS commented on index.js
> +        }
redundant arrKeys

2022-04-29 21:20 UTC, SvineruS commented on index.js
> +        let arr = a[i];
use `for .. of `syntax

2022-04-29 21:20 UTC, SvineruS commented on index.js
> +let obj = {};
don't use global vars

2022-04-29 21:20 UTC, SvineruS commented on index.js
> +
нихуя не понятно

2022-04-29 21:20 UTC, SvineruS commented on index.js
> +
нихуя не понятно
иди нахуй

2022-04-29 21:37 UTC, SvineruS commented on index.js
> +
for (let key of arr) 
    obj[key] += arr[key]

2022-04-29 22:59 UTC, krolik1591 commented
Сам иди нахуй

сб, 30 апр. 2022 г., 00:37 SvineruS ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In index.js
> <https://github.com/krolik1591/log-to-exel/pull/1#discussion_r862176465>:
>
> > +        let value = Object.values(arr);
> +        let key = Object.keys(arr);
> +
> +        for (let j = 0; j < value.length; j++) {
> +            obj[key[j]] += value[j]
> +        }
> +
>
> for (let key of arr)
>     obj[key] += arr[key]
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/krolik1591/log-to-exel/pull/1#discussion_r862176465>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYCKGYYME6SEV46L65NWORDVHRJBDANCNFSM5UXHFMOQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-30 16:49 UTC, SvineruS commented on index.js
> +}
```
function ListToCsv(list) {
    let str = ''
    for (let value of list) {
        str += value + ','
    }
    return str
}

ListToCsv(Object.keys(obj))
ListToCsv(Object.values(obj))

```

2022-04-30 16:51 UTC, SvineruS commented on index.js
> +    let str = ''
result

2022-04-30 16:51 UTC, SvineruS commented on index.js
> +    let arr = await processLineByLine('E:\\work\\test.txt')
logsList

2022-04-30 16:52 UTC, SvineruS commented on index.js
> +    await file.close()
await fs.promises.writeFile(filename, data)

2022-05-02 15:30 UTC, merged